# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://neoeinstein.github.io
gitlocation: git@github.com:neoeinstein/neoeinstein.github.io.git
gitbranch: master
gitsourceroot: https://github.com/neoeinstein/FsBlog/tree/master/
title: Grim's Scythe
subtitle: Writings on software engineering.
description: >
    Writings on software engineering focusing on my journey into functional programming practices.
    I am often found writing in F#, PowerShell, and C#. Former contributor to the Boo programming language.
    Views expressed here are mine and do not represent the views of my employer or any other party.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
